sudo: false
language: c
compiler:
  - gcc

# setup the environment
addons:
  apt:
    packages:
    - time
    - libopenmpi-dev
    - openmpi-bin

branches:
  only:
    - master
  
script:
  - make clean bin/mspar
  - mpirun --version
