language: c
compiler:
  - gcc

# setup the environment
before_install:
  # update apt-get, install dependencies
  - sudo apt-get install libopenmpi-dev openmpi-bin openmpi-doc
  - sudo apt-get autoremove

branches:
  only:
    - master
  
script:
  - make clean bin/mspar
  - mpirun --version
